version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    command: python3 app.py
    depends_on:
      - rabbitmq_container
    environment:
      - RABBIT_HOST=rabbitmq_container
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  rabbitmq_container:
    image: "rabbitmq:3.8.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq_container
  celery_tasks:
    build: .
    command: celery -A tasks worker --loglevel=info --pool=solo
    depends_on:
      - rabbitmq_container
    environment:
      - RABBIT_HOST=rabbitmq_container
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  beat_tasks:
    build: .
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - rabbitmq_container
    environment:
      - RABBIT_HOST=rabbitmq_container
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    hostname: pg_db_container

